name: promatch
description: ProMatch - Connect with Local Service Providers
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  file_picker: ^10.2.4
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  dio: ^5.3.2
  flutter_spinkit: ^5.2.0
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  flutter_local_notifications: ^19.4.0
  firebase_messaging: ^14.7.6
  firebase_core: ^2.24.2
  geocoding: ^2.1.1

  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/download.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
